title: Dans la jungle
remote_theme: oisiflorus/maquillage-danslajungle

defaults:
  - scope:
      path: ""
    values:
      layout: location

collections:
  montreal:
    output: true
  nantes:
    output: true
  montpellier:
    output: true
  bordeaux:
    output: true
  sete:
    output: true
  haute-vallee-herault:
    output: true
  lyon:
    output: true

plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-titles-from-headings
