title: Dans la jungle
remote_theme: oisiflorus/maquillage-danslajungle

collections:
  montreal:
    output: true

plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-default-layout
  - jekyll-titles-from-headings
