title: Dans la jungle
remote_theme: oisiflorus/maquillage-danslajungle

plugins:
  - jekyll-remote-theme
  - jekyll-readme-index
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-default-layout
  - jekyll-titles-from-headings
